### ISSUE TITLE
Adding "Comments" into Table of Contents?

### ISSUE THREAD

**Issue by MKDan** [projectestac/wordpress-table-of-contents-plus#2]
Is it possible to add "Comments" to the table of contents?

Example:-
...........................................................................................................................................................
**Table of Contents**	

1. H2 ( Introduction)
2. H2
3. H2 
4. H2 (Conclusion)
5. Read 52 comments to this post <----------------- possible?
...........................................................................................................................................................
I have activated 'Lazyload for comments' and this should work with it.
...........................................................................................................................................................
What is the difference between 1) https://wordpress.org/plugins/table-of-contents-plus/ and https://github.com/zedzedzed/table-of-contents-plus and this?

I need the minimized, very little JS, CSS files version. I don't want to slow down my website. Also, I needed the updated version. So, which one should I use?
...........................................................................................................................................................

**Comment by toniginard** [comment]
Hi,

This repository is a customized version of the oficial release: https://wordpress.org/plugins/table-of-contents-plus/

We don't add new functionalities unless we need them (this is not the case). You can try to ask to the developers of the original plugin (linked above), but I'm not very optimistic about it because the plugin seem abandoned.


Best wishes,
Toni Ginard
